# -*- coding: utf-8 -*-
"""CLASE 08 DE SEPT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_zn6eQaLGJXpsKLBQfdHS_azxQKssWqO

<center>

#**COLEGIO SIGLO XXI - EL SOCORRO**
#**PRESENTADO A:**  *ING. PAOLA ANDREA QUINTERO*
#**PRESENTADO POR:**  *MARCO DAVID POSSO SÁNCHEZ*
#**GRADO DÉCIMO**
#**8 DE SEPTIEMBRE 2022**

#**¿QUÉ ES PYTHON?**
#  Python es un lenguaje de programación de alto nivel que se utiliza para desarrollar aplicaciones de todo tipo. A diferencia de otros lenguajes como Java o .NET, se trata de un lenguaje interpretado, es decir, que no es necesario compilarlo para ejecutar las aplicaciones escritas en Python, sino que se ejecutan directamente por el ordenador utilizando un programa denominado interpretador, por lo que no es necesario “traducirlo” a lenguaje máquina. 

#**FECHA DE LANZAMIENTO:**
#Guido Van Rossum publicó la primera versión del código Python (versión 0.9.0) en 1991. Dicha versión ya incluía buenas características, como algunos tipos de datos y funciones para la gestión de errores.

#**Recuperado de:** 
#*https://www.becas-santander.com/es/blog/python-que-es.html*
#*https://aws.amazon.com/es/what-is/python/*
"""

print("Esto es una suma")
numero_uno = 4
numero_dos = 8
resultado = numero_uno + numero_dos
print(resultado)

print("Esto es una resta")
numero_uno = 6
numero_dos = 2
resultado = numero_uno - numero_dos
print(resultado)

print("Esto es una multiplicación")
numero_uno = 7
numero_dos = 5
resultado = numero_uno * numero_dos
print(resultado)

print("Esto es una división")
numero_uno = 9
numero_dos = 3
resultado = numero_uno / numero_dos
print(resultado)

"""#Ejercicios de Tipos de Datos Simples

##Ejercicio 1

Escribir un programa que pregunte el nombre del usuario en la consola y un número entero e imprima por pantallas en líneas distintas el nombre del usuario tantas veces como el número introducido.
"""

nombre = input("¿Como te llamas?")
n = input("Introduce un numero entero:")
print((nombre + "\n")* int(n))

"""##Ejercicio 2
Escribir un programa que pida al usuario du peso (en kg) y estatura (en metros), calcule el índice de masa corporal y lo almacene en una variable, e imprima por pantalla la frase `Tu índice de masa corporal es <imc>` donde `<imc>` es el índice de masa corporal calculado redondeando con dos decimales.
"""

peso = input("¿Cuál es tu peso en kg?")
estatura = input("¿Cuál es tu estatura en metros?")
imc = round(float(peso)/float(estatura)**2,2)
print("Tu índice de masa corporal es " + str(imc))

"""#**LIBRERÍAS EN PYTHON**"""